__tests__/resource.js, lib/resolver.content.js
This is a small fix for our friends at https://www.yapo.cl/ and its a feature we want to have. I call this a small fix because this PR implement it only on the `.stream()` methods.
This does make it possible to get hold of the http headers of a podlet. This is handy and in yapo's case nessessery to be able to use Podium in the process of breaking up an old monolith site.
For `.stream()` this is implemented as a `headers` event which always will be emitted before body starts being written to the stream. It works like this:
```js
const component = client.register({
name: 'foo',
uri: 'http://foo.site.com/manifest.json',
});
const stream = component.stream();
stream.on('headers', headers => {
console.log(headers);
});
stream.pipe(process.stdout);
```
This is **NOT** implemented on the …
=> Expose headers of the podlet on .stream()

README.md, __tests__/integration.basic.js, lib/resolver.content.js, lib/state.js
This makes it possible to set http headers on the outgoing http request to the content URLs:
```js
podlet.fetch({}, {
headers: {
foo: 'bar'
}
});
```
If a property set to `header` on the `.fetch()` or `.stream()` method collide with a property in the context or with the user-agent property, it will be overwritten by the context and user-agent property set by Podium.
=> Make it possible to set headers on the content requests

lib/client.js
To deal with a `MaxListenersExceededWarning` when setting error events on the metric streams, we did set the Max Listeners on the metrics object to a given value to supress this warning. This is now [handeled by in the metric client](https://github.com/metrics-js/client/pull/23) instead. This removes the Max Listeners setting in this module.
=> Remove the metric max listeners setting

lib/client.js
The internal cache is a stream which we use to exchange manifest data between the client and the proxy. Listen for `error` events on this stream.
=> Listen for error events on the internal cache

lib/resolver.content.js, lib/state.js
Based on a bit more info we now get from our logs in production it seems like there are some method which uses `readable-stream` in the layout causing some uncaught exceptions.
```sh
Error: write after end
at writeAfterEnd (/home/node/src/node_modules/@podium/layout/node_modules/readable-stream/lib/_stream_writable.js:257:12)
at Writable.write (/home/node/src/node_modules/@podium/layout/node_modules/readable-stream/lib/_stream_writable.js:301:21)
at Readable.ondata (/home/node/src/node_modules/@podium/layout/node_modules/readable-stream/lib/_stream_readable.js:640:20)
at Readable.read (/home/node/src/node_modules/@podium/layout/node_modules/readable-stream/lib/_stream_readable.js:467:26)
at flow (/home/node/src/node_modules/@podium/layout/node_modules/readable-stream/lib/_stream_readable.j …
```
=> Use pipeline to stream content

__tests__/resolver.content.js, __tests__/resolver.fallback.js, __tests__/resolver.js, __tests__/resolver.manifest.js, __tests__/resource.js, lib/client.js, lib/resolver.content.js, lib/resolver.fallback.js, lib/resolver.js, lib/resolver.manifest.js, lib/resource.js
This pull request reduces metric client instantiations and piping across internal classes. Instead of each class creating their own, we instead pass an existing one around.
Ideally we should only create one client at the top/entrypoint, but because each `Resource` does a transform using the podlet name, I wasn't able to do that. 
I instead opted for each resource creating a metric client and pass it around to its resolvers. This reduces the number of creations from 5 per resource to 1. 
This resolves https://github.com/podium-lib/issues/issues/8
=> refactor: reuse metrics client internally

__tests__/resolver.content.js, lib/http-outgoing.js, lib/resolver.cache.js, lib/resolver.content.js
This is a tiny clean up off the kill switch. Its mostly moving the check for when to kill into the `HttpOutgoing` object and making the properties a bit nicer.
Can be merged into master and released on a 3.x version.
=> Kill switch cleanup

lib/resource.js
A resource metrics' transform was piped into the great infinite abyss of nothingness.
This fixes a bug which was introduced in https://github.com/podium-lib/client/pull/24
=> fix: metrics transform

__tests__/client.register.js, lib/client.js, package.json
Uses strict validation of the uri to podlets manifest since they are always absolute uris.
=> Use strict validation of manifest uri

lib/client.js
During #27 we lost public exposure of the registry. We need this exposed so the `@podium/client` and `@podium/proxy` can exchange manifest files with each other in `@podium/layout`.
=> Expose registry

package.json, test/faker/index.js
To test the client there is a small helper podlet server one can adjust run time. This one is pretty generic and have previously been built on top of Express.js.
Since Podium now are http framework free this does remove Express.js and uses the plain node.js http server instead.
The initial plan for this fake podlet server is to move it into a test util package since we need a simmilar fake podlet server to test stuff in other modules (@podium/proxy, @podium/hapi-layout, @podium/fastify-layout  etc). The removal of Express.js before branching this into a separate package is done here to make sure tests here pass first.
=> Removed Express in the fake podlet server

__tests__/response.js, lib/response.js
In https://github.com/podium-lib/issues/issues/12 we introduce that the `.fetch()` method returns an Object instead of a plain String with the content. This will break for all usages of `.fetch()`.
This implements a response class which will give us a proper object as we want but if used directly in ex a template String will return the content of itself. 
Example:
```js
const response = new Response({
content: 'foo',
headers: { foo: 'bar' },
css: ['foo'],
js: ['foo'],
});
console.log(response.content);  // returns 'foo'
console.log(response.css);      // returns ['foo']
console.log(`${response}`);     // returns 'foo'
console.log(response + 'bar');  // returns 'foobar'
```
The idea is that where we now make a Object literal on `.fetch()` and the pre event for `.stream()` we create an …
=> Add a Response class which can deal with backwards compabillity

__tests__/assets.compabillity.js, __tests__/client.js, __tests__/integration.basic.js, __tests__/resolver.manifest.js, __tests__/resource.js, lib/client.js, lib/resolver.content.js, lib/resolver.manifest.js, lib/resource.js, test/faker/index.js
This PR uses the new json-schema and the V4 format of the manifest while maintaining backwards compabillity for the V3 format of the manifest.
The compabillity works as follow:
- The old methods `client.js()` and `client.css()` returns an Array of Strings as before to prevent breakage with apps using those.
- When using the new feature where `poldet.fetch()` returns a Object instead of a String, the `.css` and `.js` properties on this Object returns Arrays with the new asset Object (`{ type: 'module', value: 'a.js' }`).
- When using the new `beforeStream` event on the `podlet.stream()` method, the emitted Object holds simmilar `.js` and `.css` properties to the new returned Object on `podlet.fetch()`.
This PR does hold one test file only dealing with backwards compabillity tests plus …
=> Use new json-schema

README.md, __tests__/integration.basic.js, __tests__/resource.js, lib/resolver.content.js, lib/resource.js
This should make the returned result form `.fetch()` backwards compatible. 
Ex; new integrations should use:
```js
const res = await podlet.fetch();
console.log(`content: ${res.content}`);  // <section>component html</section>
```
Old usage should also work:
```js
const res = await podlet.fetch();
console.log(`content: ${res}`);  // <section>component html</section>
```
=> Use the response class for backwards compabillity

__tests__/integration.basic.js, __tests__/resource.js, lib/client.js, lib/resolver.content.js, lib/resolver.fallback.js, lib/resolver.manifest.js, lib/resource.js
pattern for metric names is:
`podium_<module name>_<file or class name>_<method name>`
which results in the following metric names:
* podium_client_resolver_manifest_resolve
* podium_client_resolver_fallback_resolve
* podium_client_resolver_content_resolve
* podium_client_refresh_manifests
All are histograms.
=> rename metrics, change metrics to use metric classes

README.md, __tests__/integration.basic.js, lib/http-outgoing.js, lib/resolver.content.js, lib/resource.js, lib/utils.js, package.json
This makes the `.fetch()` and `.stream()` methods take [HttpIncoming](https://github.com/podium-lib/utils/blob/master/lib/http-incoming.js) as first argument instead of just the context. HttpIncoming does store the context internally.
In other words, instead of doing this in an Express app:
```js
app.use(layout.middleware());
app.get('/', async (req, res, next) => {
const ctx = res.locals.podium.context;
const r = await podlet.fetch(ctx);
res.send(r.content);
});
```
One should now do this:
```js
app.use(layout.middleware());
app.get('/', async (req, res, next) => {
const r = await podlet.fetch(res.locals.podium);
res.send(r.content);
});
```
The advantages of this now is that we don't need to copy the context around between the middleware generating it and internally in the client. …
=> Make .fetch() and .stream() take HttpIncoming instead of just context

__tests__/client.css.js, __tests__/client.js, __tests__/client.js.js, __tests__/client.on.change.js, __tests__/client.register.js, __tests__/integration.basic.js, __tests__/resolver.manifest.js, __tests__/resource.js, lib/client.js, lib/resolver.content.js, lib/resolver.fallback.js, lib/resolver.js, lib/resolver.manifest.js
This PR adds a new required `name` field to the client constructor that is then passed down for use in the various resolver metrics
=> Add metric name label

__tests__/http-outgoing.js, __tests__/resolver.content.js, package.json
Replaces the internal destination stream helpers method with the one in @podium/test-utils.
=> Use @podium/test-utils for destination stream

__tests__/integration.basic.js, lib/resolver.content.js, lib/resolver.manifest.js, package.json
This fixes a bug where `pathname` added to the `.fetch()` and `.stream()` method was cached together with the manifest and not set again if these methods was called a second time with another value for `pathname`.
=> Pathname is not appended to content URL on request

lib/utils.js
In Podium V4 we made it so that the client has a relation to `HttpIncoming`. This should be passed on to the client as the first arguments to `.fetch()` and `.stream()`. Previously the first argument to these methods only took the context.
Though, for backwards compatibility these methods now, in V4, support arbitrary values. In a future version of Podium we want to remove the support for arbitrary values and require a `HttpIncoming` object to be passed in.
This ads a deprecation warning which is printed when arbitrary values are passed in as the first argument to `.fetch()` and `.stream()`.
=> Print deprecation warning on arbitrary values to .fetch() and .stream()

__tests__/assets.compatibility.js, __tests__/resolver.manifest.js, lib/client.js, lib/resolver.manifest.js
In V3 the manifest could hold only one String value for js and css. This value could be either an absolute URL or a relative path.
When the client reads the manifest and finds a relative value it would leave it untouched unless the client was instructed to resolve the relative value to an absolute URL for these by setting the `resolveJs` and `resolveCss` properties to true when a podlet was registered in the client. In other words; if one defined relative paths in a podlet this value would come out relative when used in a layout unless one set a property to resolve it.
At FINN.no we have kinda abused this relative path a bit in our custom asset bundling system and in our rework of this its clear that not resolving these relative paths by default in not ideal.
What we want is that the …
=> Always resolve assets on the response object

__tests__/assets.compatibility.js, __tests__/resolver.manifest.js, __tests__/resource.js, lib/resolver.manifest.js, package.json
This uses the new asset classes to create CSS and JS object instances when reading the manifest.
=> Use asset classes when parsing manifest

__tests__/assets.compatibility.js, lib/resolver.manifest.js, package.json
If the `resolveJs` or `resolveCss` option was specified for a podlet with no assets, then the v3 compatibility would use an empty string together with the manifest URL to create an absolute URL for that asset. 
This means that we got an asset URL that points to the manifest server, not an asset, even though we never specified assets.
=> Resolve assets v3 compatibility bug with empty assets

lib/resolver.content.js, lib/resolver.fallback.js, lib/resolver.manifest.js
Turns out that the histogram metrics created on requesting the manifest, fallback and content from a podlets generate a bit too much info. This is a small clean up to reduce the amount of metrics created.
Previously there was no set buckets when timing the requests so the amount of buckets did grow out of control. There are now defined 7 buckets: `[0.001, 0.01, 0.1, 0.5, 1, 2, 10]`.
The `method` label is removed due to the fact that podium only does `GET` methods so there is no need for such a label.
The `code`, `statusCode` and `status` labels serve kinda similar purpose that they tell if some thing went wrong or not. I've chosen to remove `code` and `statusCode` and keep `status`. The result of this is that we will not get fine grained metrics on different http status codes in the …
=> Tune metrics

lib/resolver.fallback.js
Currently there are generated fallback metrics on each request due to the metrics being set and timed before the is cached check in the fallback resolver. The fallback resolver should only generate metrics for the process of reading the fallback over http. This makes sure we only generate relevant metrics for when fetching the fallback.
If a fallback is being used or not are generated elsewhere.
=> Do not log metrics on cached fallback resolves

lib/client.js, lib/resolver.content.js, lib/resolver.fallback.js, lib/resolver.manifest.js
also move metric class instantiation into constructors.
I noticed a few too many metrics coming from refresh manifests which we still use due to Asset Pipe v2 in Finn Podium abstractions. While this will be going away soon, it still seemed worth it to clean this up now.
We should update tests in layout after this change to make sure the name label comes through as expected.
=> add buckets to refresh manifests method

__tests__/client.js, __tests__/resolver.manifest.js, __tests__/state.js, package.json
According to the lolex npm page, lolex has been renamed to @sinonjs/fake-timers and republished under that name. Lolex will I imagine, no longer receive updates so thought I would swap it over.
=> replace lolex with @sinonjs/fake-timers

README.md, lib/http-outgoing.js, lib/resolver.content.js, lib/resource.js, lib/response.js, package.json, test/resolver.content.js, test/resource.js, test/response.js
~~waiting on changes here: https://github.com/podium-lib/test-utils/pull/22 to land this but is otherwise done so feel free to review.~~
~~1. turns off requests default behavior to follow 3xx redirects~~
~~2. enhances error object with `redirectUrl` and and `isRedirect` boolean property~~
After discussion with @trygve-lie we decided to take a different approach. This approach has now been applied to this PR.
* A new register flag has been added `redirectable` which defaults to `false` Everything behaves as before when this is set to `false`
* When `redirectable` is `true`, redirects from a podlet will not be followed by the client and a new `response.redirect` property will be populated with the keys `statusCode` and `location` which can then be acted upon by the user
=> improve redirect error decoration

lib/http-outgoing.js, lib/resource.js, lib/utils.js, test/assets.compatibility.js, test/client.css.js, test/client.js, test/client.js.js, test/client.on.change.js, test/integration.basic.js, test/resolver.content.js, test/resolver.fallback.js, test/resolver.manifest.js, test/resource.js
BREAKING CHANGE: `HttpIncoming` must now be passed as the first argument to `.fetch()` and `.stream()`.
Previously it was possible to call `.fetch()` and `.stream()` with an arbitrary object (previously just the context) as the first argument. This is now not longer possible. A `HttpIncoming` object must be passed on.
Solves: https://github.com/podium-lib/issues/issues/22
=> feat: Make HttpIncoming required as first argument to .fetch() and .stream()

.eslintrc, lib/client.js, lib/http-outgoing.js, lib/resolver.cache.js, lib/resolver.content.js, lib/resolver.fallback.js, lib/resolver.js, lib/resolver.manifest.js, lib/resource.js, lib/response.js, lib/state.js, package.json
BREAKING CHANGE: Due to dropping node 10.x support we use ES private properties instead of Symbols and `.defineProperty()`.
We've been using Symbols and `.defineProperty()` to define private properties in classes up until now. This has the downside that they are not true private and in later versions of node.js one would see these Symbols when inspecting an object. What we want is proper private properties.
This PR does also add a pretty printer which outputs an object literal or the object so when debugging one can see the getters and setters of the object.
Example: printing a object with `console.log()` would previously print the following:
```sh
PodiumClientResponse {
[Symbol(podium:client:response:redirect)]: '',
[Symbol(podium:client:response:content)]: '', …
```
=> feat: Use ES private properties instead of Symbols and defineProperty() for privacy

lib/resource.js, test/integration.basic.js, test/resource.js
`.stream` method was not handling promise rejections from resource.resolve so if the resolve method rejected (eg. if resource was marked as throwable) then we got an unhandled promise rejection warning. This PR adds a catch and then just emits the error on the stream.
=> fix: emit errors on stream when .resolve method rejects

lib/http-outgoing.js, lib/resolver.content.js, lib/resource.js, package.json, test/http-outgoing.js, test/resource.js
Use native `stream` instead of `readable-stream`. Native streams have gotten a good amount of improvements in latest major versions of node and due to dropping support for older node versions we can rely on native streams over `readable-stream`.
=> feat: Use native streams

lib/resolver.content.js
When a podlet is registered with `throwable: true` the implementer has the error and should act upon it in as she wishes. This should also include logging. Due to this, there is no reason why podium should log internally at such as a high level as `warn` on http errors.
This lowers the log level to `debug` on http errors when a podlet is registered with `throwable: true`. We keep the log level to `debug` so in development one can draw value from it.
=> fix: Lower log level when throwable is true

lib/http.js, lib/resolver.content.js, lib/resolver.fallback.js, lib/resolver.js, lib/resolver.manifest.js, lib/resource.js, lib/response.js, package.json, test/integration.basic.js, test/resolver.content.js, test/resource.js
This PR is a first pass replacing Request with Undici.
The request module is deprecated and Undici offers the potential for large performance gains.
So far, I have no idea about perf but the tests are all passing with little to no change (will explain the test changes as comments on the line numbers in this PR)
There are quite a few ways to use Undici including:
* Creating a client first and making requests with it.
* Using the request method
* Using the Fetch API.
I suspect we may want to use the client approach for perf reasons (still navigating the Undici landscape so unsure) but my initial attempts to use it were unsuccessful. The Fetch API is potentially still unstable so I have avoided that. I have therefore used the request method in this PR for now.
@trygve-lie we've talked about …
=> Replace request with Undici

lib/resolver.manifest.js, test/resolver.manifest.js
This introduces support for the new data structure for the proxy feature in the manifest. 
Current data structure is as follow:
```js
{
name: 'bar',
proxy: {
bar: 'http://foo.com/bar',
}
}
```
New data structure is as an Array of proxy Objects as follow:
```js
{
name: 'bar',
proxy: [
{name: 'bar', target: 'http://foo.com/bar'},
]
}
```
This appends a check to see if the manifest in a podlet uses the old data structure or the new data structure. If the old data structure are in use, it will be converted to the new data structure internally and used internally of a Layout.
The approach here is that version 5 of Podium will have a Layout which can understand both the old and new data structure but Podlets are still using the old data structure. In version 6 Podlets will start using the new …
=> feat: Support new proxy structure in manifest

lib/resolver.content.js
Sets log level to `debug` when there is a network error and the podlet registered is set to be throwable. When in a throwable mode the error object is forwarded and something the consumer can act upon so no need to do logging higher than debug here.
=> fix: Set log level for network errors to debug when throwable

lib/resolver.content.js
This fixes an bug where a version change in a podlet causes the client to terminate the request to the podlets content due to detecting a version change, but instead of re-fetching the manifest etc it closes the connection and resolves with the fallback. This causes the client to never re-fetch the manifest and fallback of a podlet.
The roots cause are these changes in node.js 14 (iow; these error started with node 14): https://github.com/nodejs/node/pull/32182 https://github.com/nodejs/node/issues/32225
When requesting a podlet the client needs to listen for errors in case of network issues. In the case of a network error the client will then return the fallback it has. But we also need to detect an update of a podlet (version change) and in the case of a update, the ongoing request to …
=> fix: Replace .abort() with .destroy()

.github/workflows/publish.yml, .github/workflows/test.yml, README.md, lib/http-outgoing.js, lib/resolver.content.js, lib/resource.js, lib/utils.js, package.json, test/resource.js, test/utils.js
This PR implements asset filtering in the Podium client based on the new asset scope field as added in this PR https://github.com/podium-lib/utils/pull/212
**TODO:** 
**The details**
* I've added a new isFallback property to the outgoing object so that its possible to know if the response from .fetch/.stream is content or fallback (which therefore makes it possible to filter assets)
* Fixed a bug where the `beforeStream` event was not being emitted when the client falls back. With this change beforeStream is emitted when using the .stream() method but as a side effect, it is also being emitted when .fetch() is being called although it seems unlikely anyone would use this or even notice.
* Tests that verify backwards compatibility as well as new functionality
=> Implement usage of manifest scope field

lib/http.js, package.json, test/integration.basic.js
Currently there is a situation where request from a version 5 layout to a erroring version 4 podlet ends up hanging. This removes the use of the client and just uses the request function.
This is not super optimal but works as a fix until we have landed a more thought through http client which we have started on here: https://github.com/podium-lib/http-client
=> fix: Requests hang on http errors

lib/response.js, tests/response.test.js
Avoid returning class type, instead returning the toJSON of css and js assets.
=> fix: make response toJSON return type serializable

lib/http.js, lib/resolver.content.js, tests/http.test.js
Undici wasn't respecting body timeouts which was more likely more our misunderstanding of how it works than a bug
https://github.com/nodejs/undici/issues/3297
=> fix: use AbortSignal to ensure timeouts are respected

lib/http.js
With this PR, we replace `AbortSignal.timeout()` with the more general `AbortController.abort()` in combination with `setTimeout`. This change prevents an unhandled exception propagating up outside the scope of the calling function.
Fixes https://github.com/podium-lib/client/issues/411
=> fix: use AbortController instead of AbortSignal to avoid unhandled exception

lib/http-outgoing.js, lib/http.js, lib/resolver.content.js, lib/resolver.fallback.js, lib/resource.js, lib/utils.js, package.json, tests/http-outgoing.test.js, tests/integration.basic.test.js, tests/resolver.cache.test.js, tests/resolver.content.test.js, tests/resolver.fallback.test.js, tests/resolver.manifest.test.js, tests/resolver.test.js, tests/resource.test.js, tsconfig.json
Adds support for reading assets from podlets via 103 early hints. Does not change the API surface for developers, this is purely an under the hood change.
* Implements phase 1: https://github.com/podium-lib/client/pull/410#issuecomment-2323536976
* Replaces: https://github.com/podium-lib/client/pull/410
=> feat: read assets from podlets using 103 early hints

lib/resolver.content.js, lib/resolver.fallback.js, lib/resolver.manifest.js
This adds more useful error messages for when the client times out due to AbortController timeout being reached
=> fix: improve error messages when fetching from manifest, content and fallback routes when a timeout occurs

README.md, lib/client.js, lib/http-outgoing.js, lib/resolver.content.js, lib/resolver.js, package.json, tests/http-outgoing.test.js, tests/integration.basic.test.js, tests/resolver.content.test.js
Phase 2.
Write the early hints from the podlet, out to the browser. Once again, backwards compatible, no breaking changes.
=> Write early hints to browser

lib/resolver.content.js
```
AssertError: The error is not compatible with boom
at internals.initialize (/app/node_modules/@hapi/boom/lib/index.js:430:14)
at exports.boomify (/app/node_modules/@hapi/boom/lib/index.js:126:26)
at internals.serverError (/app/node_modules/@hapi/boom/lib/index.js:460:24)
at exports.badGateway (/app/node_modules/@hapi/boom/lib/index.js:377:22)
at PodletClientContentResolver.resolve (file:///app/node_modules/@podium/client/lib/resolver.content.js:290:23)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async PodiumClientResource.fetch (file:///app/node_modules/@podium/client/lib/resource.js:163:13)
at async Promise.all (index 0)
at async Object.<anonymous> (file:///app/src/create-server.js:313:41)
```
=> fix: throw boom compatible error on badGateway for throwable podlet

lib/resolver.content.js
The sentiment for doing this is to reduce the log out put from something which isn't really an erroring state (that something isn't found), reducing it to `debug` will reduce noise from applications which use `throwable` and when their podlets returnin `http 404`.
=> fix: reducing logl evel to debug on 404 errors

lib/resolver.content.js, lib/resolver.fallback.js, lib/utils.js, tests/integration.basic.test.js
This essentially boils down to me missing the need for a call to uriRelativeToAbsolute when parsing assets from link headers. This is the function that combines the origin of the podlet with any relative asset paths to ensure that requests from the client go to the podlet to fetch its assets instead of trying to fetch from the layout.
eg. layout is on localhost:8080 and the podlet is on localhost:8081
the podlet has a relative asset path of /static/scripts.js 
Before this fix, the layout was trying to fetch from localhost:8080/static/scripts.js when it should have been trying to fetch from localhost:8081/static/scripts.
=> fix: correctly build asset urls from link headers

package.json
Figured I could add the option of imports without `lib/` in the path, but keeping both for backward compatibility.
=> fix: list exports so types work for imports other than root

lib/client.js, tests/integration.basic.test.js
I've added this metric to give us a way to be able to answer the following questions:
* how many podlets does a layout have registered?
* which layouts is my podlet registered in?
=> feat: add metric to track register podlets

lib/resolver.cache.js, package-lock.json, package.json
This replacement with a shallow clone might look odd, but only one value at the root level is mutated. Also, because of a quirk with how clonedeep works with the AssetCss and AssetJs classes in podium utils, the entries in the css and js arrays weren't actually cloned – instead the values were copied.
See https://github.com/podium-lib/utils/pull/289 for a more thorough explanation with links to code.
=> fix(deps): remove clonedeep dependency

lib/http-outgoing.js
This makes it much easier to link OpenTelemetry traces between a layout and its podlets. It's been possible before, but required userland code to forward the headers in each fetch call. With this, all users should need to get a distributed trace is to insrument the layout and podlets with the OpenTelemetry SDK.
- [Getting started with OpenTelemetry for Node](https://opentelemetry.io/docs/languages/js/getting-started/nodejs/).
- [About context propagation, distributed traces, using `traceparent` and `tracestate`](https://opentelemetry.io/docs/concepts/context-propagation/).
Screenshot of a distributed trace visualized in [Jaeger](https://www.jaegertracing.io). Here the layout requests five podlets, but only one of them are set up with OpenTelemetry instrumentation. We still get a good idea …
=> feat: forward traceparent and tracestate headers
